/* mon_funcs2.js
//
// Release: v2.0 July 2013
//
// Author: Tim Daish BA(Hons) MBCS CTAL-TM
//         Technical Consultant, NCC Group Web Performance
//
// Function Library for demo pages for API and Error Feeds in XML formats
//
*/
if(!window.console)console={log:function(){}};var tst_status="";var tst_type="";var sRowColor="";var sRow="";var sFontSize="";var sImage="";var sLTDSW="";var sLTDSD="";var sKpi="";var sSpeedKpi="";var kpi_diff=0;var iNoofMonitorsInError=0;var sNoofMonitorsInError="";var countOK=0;var countProblem=0;var countWarning=0;var countDown=0;var summary="";var RBEstatus=new Boolean;var obstext="";var aResultCodes=new Array;
function updateClock(){var currentTime=new Date;var currentHours=currentTime.getHours();var currentMinutes=currentTime.getMinutes();var currentSeconds=currentTime.getSeconds();currentMinutes=(currentMinutes<10?"0":"")+currentMinutes;currentSeconds=(currentSeconds<10?"0":"")+currentSeconds;var timeOfDay=currentHours<12?"AM":"PM";currentHours=currentHours==0?12:currentHours;var currentTimeString=currentHours+":"+currentMinutes+":"+currentSeconds+" "+timeOfDay;$("#jq4uclock").html(currentTimeString)}
function setRBE(){RBEstatus=document.getElementById("rbe").checked;if(RBEstatus==true)alert("RBE filter will be applied at next refresh");else alert("RBE filter will be removed at next refresh")}function BreakNumber(num){return FormattedNumberWhole(num)+"."+FormattedNumberDecimal(num)}function FormattedNumberWhole(numw){digits=parseInt(numw,10).toFixed();if(digits>9)return digits;else return"0"+parseInt(numw,10).toFixed()}
function FormattedNumberDecimal(numd){digits=parseInt(numd,10).toFixed();if(digits>99)return parseFloat(numd).toFixed(1).substr(3,2);else if(digits>9)return parseFloat(numd).toFixed(1).substr(2,2);else return parseFloat(numd).toFixed(1).substr(1,2)}function CheckKPIMet(speed,kpi){if(kpi==0)return"";return Math.round(kpi-speed)}
function initgauges(){var sections=Array(steelseries.Section(0,3,"rgba(84, 0, 0, 0.8)"),steelseries.Section(3,10,"rgba(238, 154, 0, 0.8)"),steelseries.Section(10,30,"rgba(0, 0, 255, 0.3)"));var sections_page=Array(steelseries.Section(0,7,"rgba(0, 255, 0, 0.3)"),steelseries.Section(7,20,"rgba(238, 154, 0, 0.8)"),steelseries.Section(20,30,"rgba(84, 0, 0, 0.8)"));var sections_uj=Array(steelseries.Section(0,30,"rgba(0, 255, 0, 0.3)"),steelseries.Section(30,40,"rgba(238, 154, 0, 0.8)"),steelseries.Section(40,
60,"rgba(84, 0, 0, 0.8)"));var sections_ws=Array(steelseries.Section(0,1,"rgba(0, 255, 0, 0.3)"),steelseries.Section(1,3,"rgba(238, 154, 0, 0.8)"),steelseries.Section(3,10,"rgba(84, 0, 0, 0.8)"));var areas=Array(steelseries.Section(10,40,"rgba(0, 255,0, 0.3)"));var area_page=Array(steelseries.Section(0,7,"rgba(0, 255,0, 0.3)"));var area_uj=Array(steelseries.Section(0,30,"rgba(0, 255,0, 0.3)"));var area_ws=Array(steelseries.Section(0,1,"rgba(0, 255,0, 0.3)"));gauge1_ss=new steelseries.Radial("canvas_ss_gauge1",
{size:300,section:sections_page,area:area_page,minValue:0,maxValue:30,threshold:7,titleString:"Page Average",unitString:"seconds",frameDesign:steelseries.FrameDesign.STEEL,backgroundColor:steelseries.BackgroundColor.LIGHT_GRAY,pointerType:steelseries.PointerType.TYPE8,pointerColor:steelseries.ColorDef.BLUE,lcdColor:steelseries.LcdColor.WHITE,ledColor:steelseries.LedColor.YELLOW_LED,lcdDecimals:1});gauge2_ss=new steelseries.Radial("canvas_ss_gauge2",{size:300,section:sections_uj,area:area_uj,minValue:0,
maxValue:60,threshold:30,titleString:"UJ Average",unitString:"seconds",frameDesign:steelseries.FrameDesign.STEEL,backgroundColor:steelseries.BackgroundColor.LIGHT_GRAY,pointerType:steelseries.PointerType.TYPE8,pointerColor:steelseries.ColorDef.BLUE,lcdColor:steelseries.LcdColor.WHITE,ledColor:steelseries.LedColor.YELLOW_LED,lcdDecimals:1});gauge3_ss=new steelseries.Radial("canvas_ss_gauge3",{size:300,section:sections_ws,area:area_ws,minValue:0,maxValue:10,threshold:2,titleString:"WS Average",unitString:"seconds",
frameDesign:steelseries.FrameDesign.STEEL,backgroundColor:steelseries.BackgroundColor.LIGHT_GRAY,pointerType:steelseries.PointerType.TYPE8,pointerColor:steelseries.ColorDef.BLUE,lcdColor:steelseries.LcdColor.WHITE,ledColor:steelseries.LedColor.YELLOW_LED,lcdDecimals:1});gauge4_ss=new steelseries.RadialBargraph("canvas_ss_gauge4",{gaugeType:steelseries.GaugeType.TYPE3,titleString:"Not OK",unitString:"%",threshold:7,frameDesign:steelseries.FrameDesign.STEEL,backgroundColor:steelseries.BackgroundColor.LIGHT_GRAY,
valueColor:steelseries.ColorDef.RED,lcdColor:steelseries.LcdColor.WHITE,ledColor:steelseries.LedColor.RED_LED,lcdDecimals:1,digitalFont:true});gauge5_ss=new steelseries.RadialBargraph("canvas_ss_gauge5",{gaugeType:steelseries.GaugeType.TYPE3,titleString:"Missed KPI",unitString:"%",threshold:25,frameDesign:steelseries.FrameDesign.STEEL,backgroundColor:steelseries.BackgroundColor.LIGHT_GRAY,valueColor:steelseries.ColorDef.RED,lcdColor:steelseries.LcdColor.WHITE,ledColor:steelseries.LedColor.RED_LED,
lcdDecimals:1,digitalFont:true});gauge6_ss=new steelseries.Linear("canvas_ss_gauge6",{width:600,height:100,frameDesign:steelseries.FrameDesign.STEEL,backgroundColor:steelseries.BackgroundColor.LIGHT_GRAY,gaugeType:steelseries.GaugeType.TYPE5,titleString:"Number of Open Errors",unitString:"",threshold:0,minValue:0,maxValue:10,lcdVisible:true,lcdDecimals:0});activeled_ss=new steelseries.Led("canvas_ss_activeled",{width:50,height:50,ledColor:steelseries.LedColor.GREEN_LED});activeled_ss.blink(true);
errorled_ss=new steelseries.Led("canvas_ss_errorled",{width:120,height:120,ledColor:steelseries.LedColor.RED_LED});errorled_ss.blink(false);lastobs_ss=new steelseries.DisplaySingle("canvas_ss_lastobs",{width:500,height:40,lcdColor:steelseries.LcdColor.WHITE,value:"",autoScroll:true,valuesNumeric:false});gauge1avg_ss=new steelseries.DisplaySingle("canvas_ss_gauge1avg",{width:100,height:40,lcdColor:steelseries.LcdColor.WHITE,value:"",autoScroll:false,valuesNumeric:false,digitalFont:true});gauge1min_ss=
new steelseries.DisplaySingle("canvas_ss_gauge1min",{width:100,height:40,lcdColor:steelseries.LcdColor.WHITE,value:"",autoScroll:false,valuesNumeric:false,digitalFont:true});gauge1max_ss=new steelseries.DisplaySingle("canvas_ss_gauge1max",{width:100,height:40,lcdColor:steelseries.LcdColor.WHITE,value:"",autoScroll:false,valuesNumeric:false,digitalFont:true});gauge2avg_ss=new steelseries.DisplaySingle("canvas_ss_gauge2avg",{width:100,height:40,lcdColor:steelseries.LcdColor.WHITE,value:"",autoScroll:false,
valuesNumeric:false,digitalFont:true});gauge2min_ss=new steelseries.DisplaySingle("canvas_ss_gauge2min",{width:100,height:40,lcdColor:steelseries.LcdColor.WHITE,value:"",autoScroll:false,valuesNumeric:false,digitalFont:true});gauge2max_ss=new steelseries.DisplaySingle("canvas_ss_gauge2max",{width:100,height:40,lcdColor:steelseries.LcdColor.WHITE,value:"",autoScroll:false,valuesNumeric:false,digitalFont:true})}
$(document).ready(function(){function getData(){$.ajax({type:"GET",url:"api_getxml2.php",dataType:"xml",success:parseXml,error:function(xhr,ajaxOptions,thrownError){console.log("xml poll error");activeled_ss.blink(true);activeled_ss.setLedColor(steelseries.LedColor.RED_LED)}})}function refresh_timer(){setTimeout(refresh_timer,3E5);getData()}updateClock();myCounter=setInterval(function(){updateClock()},1E3);refresh_timer();readRClabels()});
function readRClabels(){$.ajax({type:"GET",url:"ResultCodes.xml",dataType:"xml",success:parseRCXml,error:function(xhr,ajaxOptions,thrownError){console.log("xml rc error")}})}
function parseRCXml(xml){var RCid="";var RCsev="";var RCdesc="";$(xml).find("code").each(function(){$(this).find("id").each(function(){RCid=$(this).text()});$(this).find("severity").each(function(){RCsev=$(this).text()});$(this).find("description").each(function(){RCdesc=$(this).text()});aResultCodes[Number(RCid)]=RCdesc});aResultCodes[0]="";aResultCodes[1]=""}
function parseXml(xml){countOK=0;countProblem=0;countWarning=0;countDown=0;var tag="";var tag_a="";var aMonitorTimes=new Array;aMonitorTimes[0]=new Array(3);aMonitorTimes[1]=new Array(3);aMonitorTimes[2]=new Array(3);var iMonTimeTotal=0;var iMonTimeAvg=0;var iMonTimeMin=0;var iMonTimeMax=0;var iMonTypeCount=0;var iPctOkMonitors=0;var iMonKPIMet=0;var iMonKPIMissed=0;var iPctKPIMissed=0;var sRC="";var iRC="";var now=new Date;obstext="Last poll time:"+now;$("#table#table tbody").empty();activeled_ss.setLedColor(steelseries.LedColor.RED_LED);
$(xml).find("Response").each(function(){var responseStatus=$(this).attr("Status");var responseCode=$(this).attr("Code");var responseMessage=$(this).attr("Message");if(responseStatus=="Ok"){activeled_ss.blink(true);activeled_ss.setLedColor(steelseries.LedColor.GREEN_LED);obstext=obstext+"; Polling every 5 minutes"}else obstext=obstext+"; Polling stopped - no connection to NCC Group API"});lastobs_ss.setValue(obstext);iMonKPIMet=0;iMonKPIMissed=0;for(var i=1;i<=3;i++){switch(i){case 1:tag="Page";tag_a=
"pg";break;case 2:tag="UserJourney";tag_a="uj";break;case 3:tag="WebService";tag_a="ws";break}iMonTimeTotal=0;iMonTimeAvg=0;iMonTimeMin=1E4;iMonTimeMax=0;iMonTypeCount=0;iMonTypeCount=0;$(xml).find(tag).each(function(){var label=$(this).attr("Label");if(label=="")$("table#table tbody tr").hide();else{sSpeed=$(this).attr("LastTestDownloadSpeed");sLTDSW=FormattedNumberWhole($(this).attr("LastTestDownloadSpeed"));sLTDSD=FormattedNumberDecimal($(this).attr("LastTestDownloadSpeed"));tst_status=$(this).attr("CurrentStatus");
switch(tst_status){case "OK":sRowColor="green";sFontSize="big";sImage="mon_ok.png";iRC=$(this).attr("ResultCode");sRC="";countOK=countOK+1;break;case "Warning":sRowColor="amber";sFontSize="big";sImage="mon_warning.png";iRC=$(this).attr("ResultCode");sRC=iRC+": ";countWarning=countWarning+1;break;case "Problem":sRowColor="red";sFontSize="big";sImage="mon_problem.png";iRC=$(this).attr("ResultCode");sRC=iRC+": ";countProblem=countProblem+1;break;case "Down":sRowColor="black";sFontSize="big";sImage="mon_down.png";
iRC=$(this).attr("ResultCode");sRC=iRC+": ";countDown=countDown+1;break;default:sRowColor="amber"}iMonTimeTotal=Number(iMonTimeTotal)+Number($(this).attr("LastTestDownloadSpeed"));iMonTypeCount=Number(iMonTypeCount)+1;if(Number($(this).attr("LastTestDownloadSpeed"))<Number(iMonTimeMin))iMonTimeMin=Number($(this).attr("LastTestDownloadSpeed"));if(Number($(this).attr("LastTestDownloadSpeed"))>Number(iMonTimeMax))iMonTimeMax=Number($(this).attr("LastTestDownloadSpeed"));sSpeedKpi=$(this).attr("SpeedKpi");
if(sSpeedKpi>0){kpi_diff=CheckKPIMet(sSpeed,sSpeedKpi);if(kpi_diff>=0){iMonKPIMet=Number(iMonKPIMet)+1;sKpi='<img src="images/plus.png" width="32" height="32" title="KPI met" alt="KPI met" />'+String(Math.abs(kpi_diff)+" s")}else{iMonKPIMissed=Number(iMonKPIMissed)+1;sKpi='<img src="images/minus.png" width="32" height="32" title="KPI met" alt="KPI missed" />'+String(Math.abs(kpi_diff))+" s"}}else sKpi="";sRow='<tr class="'+sRowColor+'">'+'<td width="40%"class="'+sFontSize+' left">'+' <span class="right"><img src="images/mon_'+
tag_a+'64.png" width="64" height="64" title="'+tag+'" /></span>'+$(this).attr("Label")+"</td>"+'<td width="15%" class="'+sFontSize+' left"> <img src="images/'+sImage+'" width="64" height="64" title="'+tst_status+'" />'+$(this).attr("CurrentStatus")+"</td>"+'<td  width="25%"class="'+"med"+' right"> '+sRC+aResultCodes[Number(iRC)]+"</td>"+'<td class="right"><span class="big">'+sLTDSW+"</span>"+'<span class="med">'+sLTDSD+" s</span></td>"+'<td class="'+""+'">'+$(this).attr("LastTestLocalDateTime")+"</td>"+
'<td class="'+""+'" right>'+sKpi+"</td>"+"</tr>";if(RBEstatus==false||RBEstatus==true&&tst_status!="OK")$("table#table tbody").append(sRow)}});iMonTimeAvg=(iMonTimeTotal/iMonTypeCount).toFixed(3);aMonitorTimes[i-1][0]=iMonTimeMin;aMonitorTimes[i-1][1]=iMonTimeAvg;aMonitorTimes[i-1][2]=iMonTimeMax}document.getElementById("cntok").innerHTML="OK: "+countOK.toString();document.getElementById("cntwn").innerHTML="Warning: "+countWarning.toString();document.getElementById("cntpr").innerHTML="Problem: "+
countProblem.toString();document.getElementById("cntdn").innerHTML="Down: "+countDown.toString();iNoofMonitorsInError=countProblem+countDown;sNoofMonitorsInError=iNoofMonitorsInError.toString();gauge1min_ss.setValue(aMonitorTimes[0][0]);gauge1avg_ss.setValue(aMonitorTimes[0][1]);gauge1max_ss.setValue(aMonitorTimes[0][2]);gauge2min_ss.setValue(aMonitorTimes[1][0]);gauge2avg_ss.setValue(aMonitorTimes[1][1]);gauge2max_ss.setValue(aMonitorTimes[1][2]);iPctOkMonitors=100-countOK/(countOK+countWarning+
countProblem+countDown)*100;iPctKPIMissed=iMonKPIMissed/(iMonKPIMissed+iMonKPIMet)*100;gauge1_ss.setValue(aMonitorTimes[0][1]);gauge2_ss.setValue(aMonitorTimes[1][1]);gauge3_ss.setValue(aMonitorTimes[2][1]);gauge4_ss.setValueAnimated(iPctOkMonitors);gauge5_ss.setValueAnimated(iPctKPIMissed);gauge6_ss.setValue(iNoofMonitorsInError);if(iNoofMonitorsInError>0){errorled_ss.blink(true);errorled_ss.setLedColor(steelseries.LedColor.RED_LED);errorled_ss.repaint}else{errorled_ss.blink(false);errorled_ss.resetLed;
errorled_ss.repaint}}
function feedLoaded(result){var d=new Date;var n=d.toLocaleTimeString();$("#table#table tbody").empty();if(!result.error){var content=document.getElementById("content");content.innerHTML="";var channel=$("channel",result).eq(0);var items=[];$("item",result).each(function(){var item={};item.title=$(this).find("title").eq(0).text();item.link=$(this).find("link").eq(0).text();item.description=$(this).find("description").eq(0).text();item.updated=$(this).find("pubDate").eq(0).text();item.id=$(this).find("guid").eq(0).text();
items.push(item)});var iErrorCountOpen=0;var iErrorCountClosed=0;$("item",result).each(function(){var item={};item.title=$(this).find("title").eq(0).text();item.link=$(this).find("link").eq(0).text();item.description=$(this).find("description").eq(0).text();item.updated=$(this).find("pubDate").eq(0).text();item.id=$(this).find("guid").eq(0).text();var str=item.title;var n=str.search("Open:");if(n>0){iErrorCountOpen=iErrorCountOpen+1;var itemerrno=item.title.substring(0,n-1);var f=str.search(" for ");
var itemerrsite=item.title.substring(f+4);var itemerrtitle=item.title.substring(n+6,f);var rc1=item.description.indexOf("result code")-1;var desc_s=item.description.substring(rc1);var rc2=desc_s.indexOf(".");var itemrc=desc_s.substring(12,rc2-1);sRowColor="open";sFontSize="med";var errorduration="";var errortimeopen=item.updated;var errortimeclosed="";var itemstatus="Open";var errorisclosed=new Boolean;for(var j=0;j<items.length;j++){errtitle=items[j].title;var p=errtitle.indexOf(itemerrno);if(p==
0)if(errtitle.indexOf("Closed")>0){errorisclosed=true;iErrorCountClosed=iErrorCountClosed+1;break}}var sDates="";var sDtOpen="";var sDtClosed="";var dt_Open=new Date;var dt_Closed=new Date;dt_Open=Date.parse(errortimeopen)+currentTimeZoneOffsetInHours;var sDtOpen=dateFormat(dt_Open,"isoDateTime");sDates=sDtOpen;if(dt_Open>dt_LastOpen)dt_LastOpen=dt_Open;if(errorisclosed==true){sRowColor="closed";itemstatus="Closed";errorduration="tbc";errortimeclosed=items[j].updated;dt_Closed=Date.parse(errortimeclosed)+
currentTimeZoneOffsetInHours;errorduration=Math.abs(dt_Closed-dt_Open);sDtClosed=dateFormat(dt_Closed,"isoDateTime");var diff=dt_Closed-dt_Open,sign=diff<0?-1:1,milliseconds,seconds,minutes,hours,days;diff/=sign;diff=(diff-(milliseconds=diff%1E3))/1E3;diff=(diff-(seconds=diff%60))/60;diff=(diff-(minutes=diff%60))/60;days=(diff-(hours=diff%24))/24;var sDays=" day ";if(days==0)errorduration=hours+"h "+minutes+"m "+seconds+"s";else errorduration=days+"d "+hours+"h "+minutes+"m "+seconds+"s";sDates=sDates+
"<br>"+sDtClosed}else{var dt_now=new Date;var diff=dt_now-dt_Open,sign=diff<0?-1:1,milliseconds,seconds,minutes,hours,days;diff/=sign;diff=(diff-(milliseconds=diff%1E3))/1E3;diff=(diff-(seconds=diff%60))/60;diff=(diff-(minutes=diff%60))/60;days=(diff-(hours=diff%24))/24;var sDays="d ";if(days==0)errorduration=hours+"h "+minutes+"m "+seconds+"s";else errorduration=days+"d "+hours+"h "+minutes+"m "+seconds+"s";sDates=sDates}if(iErrorCountOpen-iErrorCountClosed>0&&RBEstatus==true||RBEstatus==false){var sRow=
'<tr class="'+sRowColor+'">'+'<td width="8%"class="'+sFontSize+' left">'+itemerrno+"</td>"+'<td width="30%"class="'+sFontSize+' left">'+itemerrsite+"</td>"+'<td class="'+sFontSize+' right">'+itemerrtitle+"</td>"+'<td class="'+sFontSize+' right"> '+itemrc+"</td>"+'<td class="'+""+'">'+sDates+"</td>"+'<td class="'+""+'" right>'+itemstatus+"</td>"+'<td class="'+""+'" right>'+errorduration+"</td>"+"</tr>";if(RBEstatus==false||RBEstatus==true&&itemstatus!="Closed")$("table#table tbody").append(sRow)}else;
}});if(iErrorCountOpen-iErrorCountClosed==0){sRowColor="noerrors";var sRow='<tr class="'+sRowColor+'">'+'<td width="100%"class="'+sFontSize+' center">'+"No Recent Open Errors"+"</td>"+"</tr>";if(RBEstatus==true)$("table#table tbody").append(sRow);var dt_now=new Date;var diff=dt_now-dt_LastOpen,sign=diff<0?-1:1,milliseconds,seconds,minutes,hours,days;diff/=sign;diff=(diff-(milliseconds=diff%1E3))/1E3;diff=(diff-(seconds=diff%60))/60;diff=(diff-(minutes=diff%60))/60;days=(diff-(hours=diff%24))/24;var sDays=
" day ";if(days==0)errorduration=hours+"h "+minutes+"m";else{if(days>1)sDays=" days ";errorduration=days+"d "+hours+"h "+minutes+"m"}sRow='<tr class="'+""+'">'+'<td width="100%"class="'+sFontSize+' center">'+"time since last error: "+errorduration+"</td>"+"</tr>";if(RBEstatus==true)$("table#table tbody").append(sRow)}}else console.log("xml load error")};